const list = ["The Business Inn",
    "Whalesbone,Eyemaxx",
    "Parker Clean",
    "Red Velvet",
    "Dollarama",
    "Deacon Brodies",
    "Wine Rack",
    "Lemongrass",
    "J'adore",
    "St. Louis Bar and Grill",
    "Elgin Beer Project",
    "El Camino",
    "Datsun",
    "Leading Note Classical Print Music",
    "The Standard",
    "The Cross",
    "Town",
    "Sir John A",
    "The Fry",
    "Ginza",
    "Zesty Market",
    "Heart of Ottawa Health Centre",
    "Ministry of Coffee",
    "Fiore",
    "White Cross Pharmacy",
    "Oriental House",
    "Brown Loaf Bakery",
    "Pot & Pantry",
    "Morrison's Hair",
    "McDonald's",
    "Circle K",
    "Rio Nails",
    "Paramount Properties",
    "Common",
    "The Manx",
    "The Waverley",
    "Lietenant's Pump",
    "Hooley's",
    "Fox and the Feather",
    "Pancho Villa",
    "Pizza Pizza",
    "Elgin Fitness",
    "TD Canada Trust",
    "Live on Elgin",
    "Perfect Books",
    "Elgin Jewellers",
    "Scrim's Florist",
    "The Gifted Type",
    "Boogie and Birdie",
    "Starbucks",
    "Johnny Farina's",
    "Shawarma Andalo's",
    "Harvey's",
    "Circle K",
    "Pure Kitchen",
    "Happy Goat Coffee",
    "Captain's Boil",
    "Elgin Street Diner",
    "Pure Gelato",
    "Quickie",
    "Pirho",
    "Al's Steakhouse",
    "Hooley's",
    "Pizza Pizza",
    "TD Canada Trust",
    "Bridgehead",
    "Katari",
    "Barres and Wheeles",
    "Maclaren's",
    "Boko Bakery",
    "Dunn's Deli",
    "Chez Moi",
    "Japanese Dollar Store",
    "Kat and Kraken",
    "Brown's Cleaners",
    "Cafe Oz",
    "Kochu Sushi"
];
